/**
 * @warning This file is generated by Claude Opus 4.5
 */
#include "net.hpp"

namespace net
{
    // ========== Ipv4Addr ==========

    Ipv4Addr::Ipv4Addr(uint8_t a, uint8_t b, uint8_t c, uint8_t d)
    {
        _octets[0] = a;
        _octets[1] = b;
        _octets[2] = c;
        _octets[3] = d;
    }

    const uint8_t *Ipv4Addr::octets() const noexcept
    {
        return _octets;
    }

    uint32_t Ipv4Addr::to_bits() const noexcept
    {
        // Network byte order (big-endian)
        return (static_cast<uint32_t>(_octets[0]) << 24) |
               (static_cast<uint32_t>(_octets[1]) << 16) |
               (static_cast<uint32_t>(_octets[2]) << 8) |
               static_cast<uint32_t>(_octets[3]);
    }

    Ipv4Addr Ipv4Addr::from_bits(uint32_t bits)
    {
        return Ipv4Addr(
            static_cast<uint8_t>((bits >> 24) & 0xFF),
            static_cast<uint8_t>((bits >> 16) & 0xFF),
            static_cast<uint8_t>((bits >> 8) & 0xFF),
            static_cast<uint8_t>(bits & 0xFF));
    }

    const Ipv4Addr Ipv4Addr::LOCALHOST = Ipv4Addr(127, 0, 0, 1);
    const Ipv4Addr Ipv4Addr::UNSPECIFIED = Ipv4Addr(0, 0, 0, 0);
    const Ipv4Addr Ipv4Addr::BROADCAST = Ipv4Addr(255, 255, 255, 255);

    // ========== Ipv6Addr ==========

    Ipv6Addr::Ipv6Addr(uint16_t a, uint16_t b, uint16_t c, uint16_t d,
                       uint16_t e, uint16_t f, uint16_t g, uint16_t h)
    {
        // Store in network byte order (big-endian)
        _octets[0] = static_cast<uint8_t>((a >> 8) & 0xFF);
        _octets[1] = static_cast<uint8_t>(a & 0xFF);
        _octets[2] = static_cast<uint8_t>((b >> 8) & 0xFF);
        _octets[3] = static_cast<uint8_t>(b & 0xFF);
        _octets[4] = static_cast<uint8_t>((c >> 8) & 0xFF);
        _octets[5] = static_cast<uint8_t>(c & 0xFF);
        _octets[6] = static_cast<uint8_t>((d >> 8) & 0xFF);
        _octets[7] = static_cast<uint8_t>(d & 0xFF);
        _octets[8] = static_cast<uint8_t>((e >> 8) & 0xFF);
        _octets[9] = static_cast<uint8_t>(e & 0xFF);
        _octets[10] = static_cast<uint8_t>((f >> 8) & 0xFF);
        _octets[11] = static_cast<uint8_t>(f & 0xFF);
        _octets[12] = static_cast<uint8_t>((g >> 8) & 0xFF);
        _octets[13] = static_cast<uint8_t>(g & 0xFF);
        _octets[14] = static_cast<uint8_t>((h >> 8) & 0xFF);
        _octets[15] = static_cast<uint8_t>(h & 0xFF);
    }

    Ipv6Addr::Ipv6Addr(const uint8_t octets[16])
    {
        std::memcpy(_octets, octets, 16);
    }

    const uint8_t *Ipv6Addr::octets() const noexcept
    {
        return _octets;
    }

    void Ipv6Addr::segments(uint16_t out[8]) const noexcept
    {
        for (int i = 0; i < 8; i++)
        {
            out[i] = (static_cast<uint16_t>(_octets[i * 2]) << 8) |
                     static_cast<uint16_t>(_octets[i * 2 + 1]);
        }
    }

    const Ipv6Addr Ipv6Addr::LOCALHOST = Ipv6Addr(0, 0, 0, 0, 0, 0, 0, 1);
    const Ipv6Addr Ipv6Addr::UNSPECIFIED = Ipv6Addr(0, 0, 0, 0, 0, 0, 0, 0);

    // ========== SocketAddrV4 ==========

    SocketAddrV4::SocketAddrV4(const Ipv4Addr &ip, uint16_t port)
        : NonConstructible(NonConstructibleTag::TAG), _ip(ip), _port(port)
    {
    }

    const Ipv4Addr &SocketAddrV4::ip() const noexcept
    {
        return _ip;
    }

    uint16_t SocketAddrV4::port() const noexcept
    {
        return _port;
    }

    void SocketAddrV4::set_ip(const Ipv4Addr &ip) noexcept
    {
        _ip = ip;
    }

    void SocketAddrV4::set_port(uint16_t port) noexcept
    {
        _port = port;
    }

    _net_impl::NativeSocketAddrV4 SocketAddrV4::to_native() const
    {
        // Convert IP octets to network byte order uint32_t
        uint32_t ip_bits = (static_cast<uint32_t>(_ip.octets()[0])) |
                           (static_cast<uint32_t>(_ip.octets()[1]) << 8) |
                           (static_cast<uint32_t>(_ip.octets()[2]) << 16) |
                           (static_cast<uint32_t>(_ip.octets()[3]) << 24);
        return _net_impl::NativeSocketAddrV4(ip_bits, _port);
    }

    SocketAddrV4 SocketAddrV4::from_native(const _net_impl::NativeSocketAddrV4 &native)
    {
        // Convert network byte order uint32_t back to octets
        Ipv4Addr ip(
            static_cast<uint8_t>(native.ip & 0xFF),
            static_cast<uint8_t>((native.ip >> 8) & 0xFF),
            static_cast<uint8_t>((native.ip >> 16) & 0xFF),
            static_cast<uint8_t>((native.ip >> 24) & 0xFF));
        return SocketAddrV4(ip, native.port);
    }

    // ========== SocketAddrV6 ==========

    SocketAddrV6::SocketAddrV6(const Ipv6Addr &ip, uint16_t port, uint32_t flowinfo, uint32_t scope_id)
        : NonConstructible(NonConstructibleTag::TAG), _ip(ip), _port(port), _flowinfo(flowinfo), _scope_id(scope_id)
    {
    }

    const Ipv6Addr &SocketAddrV6::ip() const noexcept
    {
        return _ip;
    }

    uint16_t SocketAddrV6::port() const noexcept
    {
        return _port;
    }

    uint32_t SocketAddrV6::flowinfo() const noexcept
    {
        return _flowinfo;
    }

    uint32_t SocketAddrV6::scope_id() const noexcept
    {
        return _scope_id;
    }

    void SocketAddrV6::set_ip(const Ipv6Addr &ip) noexcept
    {
        _ip = ip;
    }

    void SocketAddrV6::set_port(uint16_t port) noexcept
    {
        _port = port;
    }

    void SocketAddrV6::set_flowinfo(uint32_t flowinfo) noexcept
    {
        _flowinfo = flowinfo;
    }

    void SocketAddrV6::set_scope_id(uint32_t scope_id) noexcept
    {
        _scope_id = scope_id;
    }

    _net_impl::NativeSocketAddrV6 SocketAddrV6::to_native() const
    {
        return _net_impl::NativeSocketAddrV6(_ip.octets(), _port, _flowinfo, _scope_id);
    }

    SocketAddrV6 SocketAddrV6::from_native(const _net_impl::NativeSocketAddrV6 &native)
    {
        Ipv6Addr ip(native.ip);
        return SocketAddrV6(ip, native.port, native.flowinfo, native.scope_id);
    }

    // ========== SocketAddr ==========

    SocketAddr::SocketAddr(SocketAddrV4 &&v4)
        : NonConstructible(NonConstructibleTag::TAG), _data(std::move(v4))
    {
    }

    SocketAddr::SocketAddr(SocketAddrV6 &&v6)
        : NonConstructible(NonConstructibleTag::TAG), _data(std::move(v6))
    {
    }

    SocketAddr SocketAddr::v4(SocketAddrV4 &&addr)
    {
        return SocketAddr(std::move(addr));
    }

    SocketAddr SocketAddr::v6(SocketAddrV6 &&addr)
    {
        return SocketAddr(std::move(addr));
    }

    bool SocketAddr::is_v4() const noexcept
    {
        return std::holds_alternative<SocketAddrV4>(_data);
    }

    bool SocketAddr::is_v6() const noexcept
    {
        return std::holds_alternative<SocketAddrV6>(_data);
    }

    const SocketAddrV4 &SocketAddr::as_v4() const
    {
        return std::get<SocketAddrV4>(_data);
    }

    const SocketAddrV6 &SocketAddr::as_v6() const
    {
        return std::get<SocketAddrV6>(_data);
    }

    uint16_t SocketAddr::port() const noexcept
    {
        if (is_v4())
        {
            return std::get<SocketAddrV4>(_data).port();
        }
        else
        {
            return std::get<SocketAddrV6>(_data).port();
        }
    }

    _net_impl::NativeSocketAddr SocketAddr::to_native() const
    {
        if (is_v4())
        {
            return _net_impl::NativeSocketAddr::v4(std::get<SocketAddrV4>(_data).to_native());
        }
        else
        {
            return _net_impl::NativeSocketAddr::v6(std::get<SocketAddrV6>(_data).to_native());
        }
    }

    SocketAddr SocketAddr::from_native(const _net_impl::NativeSocketAddr &native)
    {
        if (native.is_v4())
        {
            return SocketAddr::v4(SocketAddrV4::from_native(native.as_v4()));
        }
        else
        {
            return SocketAddr::v6(SocketAddrV6::from_native(native.as_v6()));
        }
    }

    // ========== TcpStream ==========

    TcpStream::TcpStream(_net_impl::NativeTcpStream &&inner)
        : NonConstructible(NonConstructibleTag::TAG), _inner(std::move(inner))
    {
    }

    io::Result<TcpStream> TcpStream::connect(const SocketAddr &addr)
    {
        auto native_result = _net_impl::NativeTcpStream::connect(addr.to_native());
        if (native_result.is_err())
        {
            return io::Result<TcpStream>::err(std::move(native_result).into_err());
        }
        return io::Result<TcpStream>::ok(TcpStream(std::move(native_result).into_ok()));
    }

    io::Result<TcpStream> TcpStream::connect(const SocketAddrV4 &addr)
    {
        auto native_result = _net_impl::NativeTcpStream::connect_v4(addr.to_native());
        if (native_result.is_err())
        {
            return io::Result<TcpStream>::err(std::move(native_result).into_err());
        }
        return io::Result<TcpStream>::ok(TcpStream(std::move(native_result).into_ok()));
    }

    io::Result<TcpStream> TcpStream::connect(const SocketAddrV6 &addr)
    {
        auto native_result = _net_impl::NativeTcpStream::connect_v6(addr.to_native());
        if (native_result.is_err())
        {
            return io::Result<TcpStream>::err(std::move(native_result).into_err());
        }
        return io::Result<TcpStream>::ok(TcpStream(std::move(native_result).into_ok()));
    }

    io::Result<SocketAddr> TcpStream::peer_addr() const
    {
        auto native_result = _inner.peer_addr();
        if (native_result.is_err())
        {
            return io::Result<SocketAddr>::err(std::move(native_result).into_err());
        }
        return io::Result<SocketAddr>::ok(SocketAddr::from_native(native_result.unwrap()));
    }

    io::Result<SocketAddr> TcpStream::local_addr() const
    {
        auto native_result = _inner.local_addr();
        if (native_result.is_err())
        {
            return io::Result<SocketAddr>::err(std::move(native_result).into_err());
        }
        return io::Result<SocketAddr>::ok(SocketAddr::from_native(native_result.unwrap()));
    }

    io::Result<std::monostate> TcpStream::shutdown(Shutdown how) const
    {
        return _inner.shutdown(static_cast<_net_impl::NativeShutdown>(how));
    }

    io::Result<TcpStream> TcpStream::try_clone() const
    {
        auto native_result = _inner.try_clone();
        if (native_result.is_err())
        {
            return io::Result<TcpStream>::err(std::move(native_result).into_err());
        }
        return io::Result<TcpStream>::ok(TcpStream(std::move(native_result).into_ok()));
    }

    io::Result<std::monostate> TcpStream::set_read_timeout(std::optional<std::chrono::milliseconds> duration) const
    {
        return _inner.set_read_timeout(duration);
    }

    io::Result<std::monostate> TcpStream::set_write_timeout(std::optional<std::chrono::milliseconds> duration) const
    {
        return _inner.set_write_timeout(duration);
    }

    io::Result<std::optional<std::chrono::milliseconds>> TcpStream::read_timeout() const
    {
        return _inner.read_timeout();
    }

    io::Result<std::optional<std::chrono::milliseconds>> TcpStream::write_timeout() const
    {
        return _inner.write_timeout();
    }

    io::Result<size_t> TcpStream::peek(std::span<char> buffer) const
    {
        return _inner.peek(buffer);
    }

    io::Result<std::monostate> TcpStream::set_nodelay(bool nodelay) const
    {
        return _inner.set_nodelay(nodelay);
    }

    io::Result<bool> TcpStream::nodelay() const
    {
        return _inner.nodelay();
    }

    io::Result<std::monostate> TcpStream::set_ttl(uint32_t ttl) const
    {
        return _inner.set_ttl(ttl);
    }

    io::Result<uint32_t> TcpStream::ttl() const
    {
        return _inner.ttl();
    }

    io::Result<std::optional<io::Error>> TcpStream::take_error() const
    {
        return _inner.take_error();
    }

    io::Result<std::monostate> TcpStream::set_nonblocking(bool nonblocking) const
    {
        return _inner.set_nonblocking(nonblocking);
    }

    io::Result<size_t> TcpStream::read(std::span<char> buffer)
    {
        return _inner.read(buffer);
    }

    io::Result<size_t> TcpStream::write(std::span<const char> buffer)
    {
        return _inner.write(buffer);
    }

    io::Result<std::monostate> TcpStream::flush()
    {
        return _inner.flush();
    }

    // ========== TcpListener ==========

    TcpListener::TcpListener(_net_impl::NativeTcpListener &&inner)
        : NonConstructible(NonConstructibleTag::TAG), _inner(std::move(inner))
    {
    }

    io::Result<TcpListener> TcpListener::bind(const SocketAddr &addr)
    {
        auto result = _net_impl::NativeTcpListener::bind(addr.to_native());
        if (result.is_err())
        {
            return io::Result<TcpListener>::err(std::move(result).into_err());
        }
        return io::Result<TcpListener>::ok(TcpListener(std::move(result).into_ok()));
    }

    io::Result<TcpListener> TcpListener::bind(const SocketAddrV4 &addr)
    {
        auto result = _net_impl::NativeTcpListener::bind_v4(addr.to_native());
        if (result.is_err())
        {
            return io::Result<TcpListener>::err(std::move(result).into_err());
        }
        return io::Result<TcpListener>::ok(TcpListener(std::move(result).into_ok()));
    }

    io::Result<TcpListener> TcpListener::bind(const SocketAddrV6 &addr)
    {
        auto result = _net_impl::NativeTcpListener::bind_v6(addr.to_native());
        if (result.is_err())
        {
            return io::Result<TcpListener>::err(std::move(result).into_err());
        }
        return io::Result<TcpListener>::ok(TcpListener(std::move(result).into_ok()));
    }

    io::Result<SocketAddr> TcpListener::local_addr() const
    {
        auto result = _inner.local_addr();
        if (result.is_err())
        {
            return io::Result<SocketAddr>::err(std::move(result).into_err());
        }
        return io::Result<SocketAddr>::ok(SocketAddr::from_native(std::move(result).into_ok()));
    }

    io::Result<std::pair<TcpStream, SocketAddr>> TcpListener::accept() const
    {
        auto result = _inner.accept();
        if (result.is_err())
        {
            return io::Result<std::pair<TcpStream, SocketAddr>>::err(std::move(result).into_err());
        }
        auto native_pair = std::move(result).into_ok();
        return io::Result<std::pair<TcpStream, SocketAddr>>::ok(
            std::make_pair(
                TcpStream(std::move(native_pair.first)),
                SocketAddr::from_native(std::move(native_pair.second))));
    }

    io::Result<TcpListener> TcpListener::try_clone() const
    {
        auto result = _inner.try_clone();
        if (result.is_err())
        {
            return io::Result<TcpListener>::err(std::move(result).into_err());
        }
        return io::Result<TcpListener>::ok(TcpListener(std::move(result).into_ok()));
    }

    io::Result<std::monostate> TcpListener::set_ttl(uint32_t ttl) const
    {
        return _inner.set_ttl(ttl);
    }

    io::Result<uint32_t> TcpListener::ttl() const
    {
        return _inner.ttl();
    }

    io::Result<std::monostate> TcpListener::set_only_v6(bool only_v6) const
    {
        return _inner.set_only_v6(only_v6);
    }

    io::Result<bool> TcpListener::only_v6() const
    {
        return _inner.only_v6();
    }

    io::Result<std::optional<io::Error>> TcpListener::take_error() const
    {
        return _inner.take_error();
    }

    io::Result<std::monostate> TcpListener::set_nonblocking(bool nonblocking) const
    {
        return _inner.set_nonblocking(nonblocking);
    }
}
