/**
 * @warning This file is generated by Claude Opus 4.5
 */
#pragma once

#include "io.hpp"
#include "win32/handle.hpp"

namespace _net_impl
{
    /**
     * @brief Possible values which can be passed to the @ref NativeTcpStream::shutdown method.
     */
    enum NativeShutdown
    {
        /** @brief The reading portion of the @ref NativeTcpStream should be shut down. */
        Read = SD_RECEIVE,
        /** @brief The writing portion of the @ref NativeTcpStream should be shut down. */
        Write = SD_SEND,
        /** @brief Both the reading and the writing portions of the @ref NativeTcpStream should be shut down. */
        Both = SD_BOTH,
    };

    /**
     * @brief An IPv4 socket address.
     */
    class NativeSocketAddrV4 : public NonConstructible
    {
    public:
        /** @brief The IPv4 address (network byte order). */
        uint32_t ip;
        /** @brief The port (host byte order). */
        uint16_t port;

        explicit NativeSocketAddrV4(uint32_t ip, uint16_t port);

        /** @brief Create from a sockaddr_in structure. */
        static NativeSocketAddrV4 from_sockaddr(const sockaddr_in &addr);

        /** @brief Convert to a sockaddr_in structure. */
        sockaddr_in to_sockaddr() const;
    };

    /**
     * @brief An IPv6 socket address.
     */
    class NativeSocketAddrV6 : public NonConstructible
    {
    public:
        /** @brief The IPv6 address (network byte order). */
        uint8_t ip[16];
        /** @brief The port (host byte order). */
        uint16_t port;
        /** @brief The flow info. */
        uint32_t flowinfo;
        /** @brief The scope ID. */
        uint32_t scope_id;

        explicit NativeSocketAddrV6(const uint8_t ip[16], uint16_t port, uint32_t flowinfo, uint32_t scope_id);

        /** @brief Create from a sockaddr_in6 structure. */
        static NativeSocketAddrV6 from_sockaddr(const sockaddr_in6 &addr);

        /** @brief Convert to a sockaddr_in6 structure. */
        sockaddr_in6 to_sockaddr() const;
    };

    /**
     * @brief A socket address, either IPv4 or IPv6.
     */
    class NativeSocketAddr : public NonConstructible
    {
    private:
        std::variant<NativeSocketAddrV4, NativeSocketAddrV6> _data;

        explicit NativeSocketAddr(NativeSocketAddrV4 &&v4);
        explicit NativeSocketAddr(NativeSocketAddrV6 &&v6);

    public:
        /** @brief Move constructor. */
        NativeSocketAddr(NativeSocketAddr &&other) noexcept;
        /** @brief Move assignment operator. */
        NativeSocketAddr &operator=(NativeSocketAddr &&other) noexcept;

        /** @brief Create an IPv4 socket address. */
        static NativeSocketAddr v4(NativeSocketAddrV4 &&v4);

        /** @brief Create an IPv6 socket address. */
        static NativeSocketAddr v6(NativeSocketAddrV6 &&v6);

        /** @brief Check if this is an IPv4 address. */
        bool is_v4() const noexcept;

        /** @brief Check if this is an IPv6 address. */
        bool is_v6() const noexcept;

        /** @brief Get the IPv4 address. Throws if this is not an IPv4 address. */
        const NativeSocketAddrV4 &as_v4() const;

        /** @brief Get the IPv6 address. Throws if this is not an IPv6 address. */
        const NativeSocketAddrV6 &as_v6() const;

        /** @brief Get the port (host byte order). */
        uint16_t port() const noexcept;
    };

    /** @brief Documentation for native implementation should not be used for reference. */
    class NativeTcpStream : public NonConstructible
    {
    private:
        SOCKET _socket;

    public:
        explicit NativeTcpStream(SOCKET socket);
        NativeTcpStream(NativeTcpStream &&other) noexcept;
        NativeTcpStream &operator=(NativeTcpStream &&other) noexcept;
        ~NativeTcpStream();

        /** @brief Connect to a remote address (IPv4). */
        static io::Result<NativeTcpStream> connect_v4(const NativeSocketAddrV4 &addr);

        /** @brief Connect to a remote address (IPv6). */
        static io::Result<NativeTcpStream> connect_v6(const NativeSocketAddrV6 &addr);

        /** @brief Connect to a remote address. */
        static io::Result<NativeTcpStream> connect(const NativeSocketAddr &addr);

        /** @brief Returns the socket address of the remote peer. */
        io::Result<NativeSocketAddr> peer_addr() const;

        /** @brief Returns the socket address of the local half of this connection. */
        io::Result<NativeSocketAddr> local_addr() const;

        /** @brief Shuts down the read, write, or both halves of this connection. */
        io::Result<std::monostate> shutdown(NativeShutdown how) const;

        /** @brief Creates a new independently owned handle to the underlying socket. */
        io::Result<NativeTcpStream> try_clone() const;

        /** @brief Sets the read timeout. */
        io::Result<std::monostate> set_read_timeout(std::optional<std::chrono::milliseconds> timeout) const;

        /** @brief Sets the write timeout. */
        io::Result<std::monostate> set_write_timeout(std::optional<std::chrono::milliseconds> timeout) const;

        /** @brief Returns the read timeout. */
        io::Result<std::optional<std::chrono::milliseconds>> read_timeout() const;

        /** @brief Returns the write timeout. */
        io::Result<std::optional<std::chrono::milliseconds>> write_timeout() const;

        /** @brief Receives data on the socket without removing it from the queue. */
        io::Result<size_t> peek(std::span<char> buffer) const;

        /** @brief Sets the value of the TCP_NODELAY option. */
        io::Result<std::monostate> set_nodelay(bool nodelay) const;

        /** @brief Gets the value of the TCP_NODELAY option. */
        io::Result<bool> nodelay() const;

        /** @brief Sets the value for the IP_TTL option. */
        io::Result<std::monostate> set_ttl(uint32_t ttl) const;

        /** @brief Gets the value of the IP_TTL option. */
        io::Result<uint32_t> ttl() const;

        /** @brief Gets the value of the SO_ERROR option. */
        io::Result<std::optional<io::Error>> take_error() const;

        /** @brief Moves this TCP stream into or out of nonblocking mode. */
        io::Result<std::monostate> set_nonblocking(bool nonblocking) const;

        /** @brief Read data from the stream. */
        io::Result<size_t> read(std::span<char> buffer) const;

        /** @brief Write data to the stream. */
        io::Result<size_t> write(std::span<const char> buffer) const;

        /** @brief Flush the stream (no-op for TCP). */
        io::Result<std::monostate> flush() const;
    };

    /**
     * @brief A TCP socket server, listening for connections.
     *
     * After creating a TcpListener by binding it to a socket address, it listens
     * for incoming TCP connections. These can be accepted by calling the accept method.
     */
    class NativeTcpListener : public NonConstructible
    {
    private:
        SOCKET _socket;

    public:
        explicit NativeTcpListener(SOCKET socket);
        NativeTcpListener(NativeTcpListener &&other) noexcept;
        NativeTcpListener &operator=(NativeTcpListener &&other) noexcept;
        ~NativeTcpListener();

        /** @brief Creates a new TcpListener bound to the specified IPv4 address. */
        static io::Result<NativeTcpListener> bind_v4(const NativeSocketAddrV4 &addr);

        /** @brief Creates a new TcpListener bound to the specified IPv6 address. */
        static io::Result<NativeTcpListener> bind_v6(const NativeSocketAddrV6 &addr);

        /** @brief Creates a new TcpListener bound to the specified address. */
        static io::Result<NativeTcpListener> bind(const NativeSocketAddr &addr);

        /** @brief Returns the local socket address of this listener. */
        io::Result<NativeSocketAddr> local_addr() const;

        /**
         * @brief Accept a new incoming connection from this listener.
         * @return A pair of the connected TcpStream and the remote address.
         */
        io::Result<std::pair<NativeTcpStream, NativeSocketAddr>> accept() const;

        /** @brief Creates a new independently owned handle to the underlying socket. */
        io::Result<NativeTcpListener> try_clone() const;

        /** @brief Sets the value for the IP_TTL option on this socket. */
        io::Result<std::monostate> set_ttl(uint32_t ttl) const;

        /** @brief Gets the value of the IP_TTL option for this socket. */
        io::Result<uint32_t> ttl() const;

        /** @brief Sets the value for the IPV6_V6ONLY option on this socket. */
        io::Result<std::monostate> set_only_v6(bool only_v6) const;

        /** @brief Gets the value of the IPV6_V6ONLY option for this socket. */
        io::Result<bool> only_v6() const;

        /** @brief Gets the value of the SO_ERROR option on this socket. */
        io::Result<std::optional<io::Error>> take_error() const;

        /** @brief Moves this TCP listener into or out of nonblocking mode. */
        io::Result<std::monostate> set_nonblocking(bool nonblocking) const;
    };
}
